Traceback (most recent call last):
  File "CivMulti.py", line 114, in <module>
IndexError: list index out of range
